HMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Hotel.urls')),
]

Hotel/urls.py
from django.urls import path,include
from .views import *
app_name='hotel'
urlpatterns = [
    # path('',include('Hotel.urls')),
    path('rooms/',RoomListView.as_view(),name='roomlist_view'),
    path('bookings/',BookingListView.as_view(),name='booking_view'),
    path('booking/cancel/<int:id>',CancelBookingView.as_view(),name = 'CancelBookingView'),    path('detail/<str:category>',RoomDetailView.as_view(),name='room_detail'),
    path('success/',RoomSuccessView.as_view(),name='room_success'),
]

Hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.


class RoomCategory(models.Model):
    category = models.CharField(max_length=50)
    rate = models.FloatField()

    def __str__(self):
        return self.category


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('YAC', 'AC'),
        ('NAC', 'NON-AC'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length = 3, choices = ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self) :
        return f'{self.number}. {dict(self.ROOM_CATEGORIES)[self.category]} Beds = {self.beds} People = {self.capacity}'

class Booking(models.Model):
    PAYMENT_STATUSES = (
        ('COM', 'PAYMENT_COMPLETE'),
        ('INC', 'PAYMENT_INCOMPLETE'),
        ('PAR', 'PAYMENT_PARTIALLY_COMPLETE'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()
    payment_status = models.CharField(max_length=3, choices=PAYMENT_STATUSES)

    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

Hotel/forms.py
from django import forms
from datetime import datetime
from django.core.exceptions import ValidationError

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])

    def check_working_hours(self, start, end):
        check_in = self.cleaned_data.get('check_in')
        check_out = self.cleaned_data.get('check_out')
        if not( check_in < start and check_out < end): #This ensures that check_in and check_out are between start and end of your working hours.
            raise ValidationError("Times beyond working hours, please enter value within working hours")
        else:
            return self.cleaned_data

Hotel/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView

from Hotel.booking_functions.availability import check_availability
from .forms import AvailabilityForm
from .models import *
# Create your views here.
class RoomListView(View):
    def get(self,request):
        rooms = Room.objects.all()
        return render(request,'Hotel/room_list_view.html',{'rooms':rooms})

# class BookingView(View):
#     def get(self,request):
#         booking = Booking.objects.all()
#         return render(request,'booking_list_view.html',{'booking':booking})


class RoomDetailView(View):
    def get(self,request,category):
        room = Room.objects.get(category=category)
        return render(request,'Hotel/room_detail_view.html',{'room':room})

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]

            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return render(request,'Hotel/successbook.html',{'booking':booking})
        else:
            return HttpResponse('All of this category of rooms are booked!! Try another one')

class BookingListView(View):
   def get(self,request):
       books = Booking.objects.all()
       return render(request,'Hotel/booking_list_view.html',{'books':books})

class RoomSuccessView(View):
    def get(self,request):
        return render(request,'Hotel/successbook.html')

class CancelBookingView(View):
    def get(self,request,id):
        room = Booking.objects.get(pk=id)
        room.delete()
        messages.success(request,'room successfully deleted','success')
        return redirect('hotel:roomlist_view')

Hotel/templates/Hotel/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'Hotel/css/booking_list_view.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome dear {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'hotel:roomlist_view' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for book in books %}
            <div class="booking">
                <img src="https://images.unsplash.com/photo-1560067174-c5a3a8f37060?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
                    alt="">
                <div class="category">
                    <h2>{{book.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{book.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{book.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{book.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{book.room.capacity}}</h3>
                </div>
                <div class="cancel"><a href="{{book.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>

  </body>

</html>

Hotel/templates/Hotel/checkout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <section>
      <div class="product">
        <img
          src="https://i.imgur.com/EHyR2nP.png"
          alt="The cover of Stubborn Attachments"
        />
        <div class="description">
          <h3>Stubborn Attachments</h3>
          <h5>$20.00</h5>
        </div>
      </div>
      <button id="checkout-button">Checkout {{checkout_id}}</button>
    </section>

  </body>
  <script>
    const checkout_id = `{{ checkout_id }}`; //Getting checkout_id from Django context.

    var stripe = Stripe("pk_test_51Hu0AzH60lA1oSooKBHVwQkZ3afq3ST2RISi3oc9G35vFQUQSMUESSorx6Sd700QYz5cY5M3Pyxf9mwZVk1nBPGu00LPxShanC");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {

      stripe.redirectToCheckout({
        sessionId:`${checkout_id}` //Passing in the checkout_id variable.
      })
      .then(function(result) {
        if (result.error) {
            alert(result.error.message);
          }
      })
      .catch(function (error) {
          console.error("Error:", error);
        })
    });
  </script>
</html>

Hotel/templates/Hotel/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="{% static 'Hotel/img/deluxe_suite2.jpg' %}">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:roomlist_view'  %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

Hotel/templates/Hotel/success.html
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
  </section>
</body>
</html>

Hotel/templates/Hotel/successbook.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Successful Room Booking</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 800px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        color: #333;
    }

    p {
        text-align: center;
        color: #666;
    }

    .button {
        display: block;
        width: 200px;
        margin: 20px auto;
        padding: 10px;
        text-align: center;
        color: #fff;
        background-color: #007bff; /* Blue */
        border-radius: 5px;
        text-decoration:none;
    }
</style>
</head>
<body>

<div class="container">
    <h1>Room Booking Successful!</h1>
    <p>Your room has been successfully booked. Thank you for choosing our service.</p>
    <p>you are booking {{ booking.room }} {{ booking }}</p>
    <a href="{% url 'hotel:roomlist_view' %}" class="button">Back to Home</a>
</div>

</body>
</html>